### ISSUE TITLE
Old code with metric not Fahrenheit

### ISSUE THREAD

**Issue by jckruger** [nebhead/irrigator#12]
Great code,

I'm working on an older version [Fixed Issue with Geocoding Timeout Occuring] (as I can't seem to figure out how to subscribe to the api 3.0 call for free without a CreditCard) and have found that if you choose metric the temperature shows something like 280 degrees.

I added in my own code an else statement in openwx.php and it shows OK now. Seems if you don't have &units= then the values are wrong

if wx_data['units'] == 'F':
	url += '&units=imperial'
else:
	url += '&units=metric'

**Comment by jckruger** [comment]
output without &units=metric (bits redacted)

"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"base":"stations","main":{"temp":292.45,"feels_like":291.79,"temp_min":291.77,"temp_max":293.87,"pressure":1017,

**Comment by nebhead** [comment]
Interesting... maybe they are returning in Kelvin if it's not specified.  Very strange.  Anyway, I can add this bit of code to ensure that we always ask for units and push a new update.

**Comment by nebhead** [comment]
Alright... pushed the change to the main branch and I hope that has it sorted.

**Comment by jckruger** [comment]
You might have to do the same at line 105. I’m using older code so can’t confirm it is necessary but I suspect it is needed there too. I’ll have to figure out the free account for v3.0 calls. I’m using the 2.5 for now

**Comment by nebhead** [comment]
> You might have to do the same at line 105. I’m using older code so can’t confirm it is necessary but I suspect it is needed there too. I’ll have to figure out the free account for v3.0 calls. I’m using the 2.5 for now

Thanks!  Added to line 105 and pushed an update.  I'm in the US and using Fahrenheit, so the calls are working for me.  But I should hope that specifying Celsius/metric should work.  And I thought they were shutting down the 2.5 API in June?  Best to switch to 3.0 soon to avoid breakage.
