### ISSUE TITLE
dashboard issues

### ISSUE THREAD

**Issue by nealw8** [nebhead/irrigator#2]
when I attempt to move to the schedule page I get "internal server error" , otherwise other feature and pages appear to work. Nealw

**Comment by nealw8** [comment]
when I attempt to move to the schedule page I get "internal server error" , otherwise other feature and pages appear to work. Nealw

**Comment by nebhead** [comment]
I'm going to try to reproduce this tomorrow on a fresh install.  But before then, can you log into your raspberry pi with ssh and go to /usr/local/bin/irrigator/logs and find the web app.err.log and webapp.out.log and post those here?

**Comment by nealw8** [comment]
here are the logs

**Comment by nealw8** [comment]
[webapp.err.log](https://github.com/nebhead/irrigator/files/11995107/webapp.err.log)
[webapp.out.log](https://github.com/nebhead/irrigator/files/11995108/webapp.out.log)

**Comment by nebhead** [comment]
> [webapp.err.log](https://github.com/nebhead/irrigator/files/11995107/webapp.err.log) [webapp.out.log](https://github.com/nebhead/irrigator/files/11995108/webapp.out.log)

Thanks!  Looks like we have an issue with a zone name missing from the settings file, but being mentioned in the schedules thus the schedules page crashes.  I should probably fix this in the future, but we can fix your current setup by modifying the settings.    

Can you also grab the irrigator.json file and send that over?  It's in `/usr/local/bin/irrigator`.  If you have any personally identifying information in there (i.e. API key or location), maybe you can replace it with something else before sending.  

Thanks!

**Comment by nealw8** [comment]
here is irrigator.json

Another issue that you might consider fixing is that the current 32 bit
version of raspberry pi os lite does not come with git. i went through
several cycles of loading irrigator that failed until i installed git

**Comment by nebhead** [comment]
> Another issue that you might consider fixing is that the current 32 bit version of raspberry pi os lite does not come with git. i went through several cycles of loading irrigator that failed until i installed git

Oh, did you use the manual installation method?  If you use the auto-installer, it should install prior to using Git.  I can fix my manual install instructions if those need to be updated, thanks for pointing this out.  

![image](https://github.com/nebhead/irrigator/assets/19876886/fb7f148e-a49a-4ad6-9d91-c76377ae8fe8)

**Comment by nebhead** [comment]
> here is irrigator.json

BTW... I didn't see the file come through.

**Comment by nealw8** [comment]
[irrigator.json.txt](https://github.com/nebhead/irrigator/files/11995478/irrigator.json.txt)

**Comment by nealw8** [comment]
it would have helped if i hit the green comment button

**Comment by nebhead** [comment]
Thank you!  I have a bug it seems.  So if you change the name of the zone, the zone name isn't changed in the schedule settings.  Then the app crashes when you attempt to access the schedules.   I can fix this in the app, however for your purposes, to fix this right now, edit your irrigator.json file to remove the zones from the schedules.  For example: 

From SSH:
```bash 
cd /usr/local/bin/irrigator
sudo nano irrigator.json
```

Change this section from: 

```json
  "schedules": {
    "FrontYard": {
      "start_time": {
        "enabled": false,
        "minute": 30,
        "hour": 6,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "*",
        "cron_string": "30 6 * * *",
        "human_readable": "At 06:30 AM",
        "active": false
      },
      "zones": {
        "zone_01": {
          "duration": 10
        },
        "zone_02": {
          "duration": 10
        }
      }
    },
    "BackYard": {
      "start_time": {
        "enabled": false,
        "minute": 0,
        "hour": 18,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "SUN,MON,TUE,WED,THU,FRI,SAT",
        "cron_string": "0 18 * * SUN,MON,TUE,WED,THU,FRI,SAT",
        "human_readable": "At 06:00 PM, only on Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday",
        "active": true
      },
      "zones": {
        "zone_01": {
          "duration": 1
        },
        "zone_02": {
          "duration": 1
        },
        "zone_03": {
          "duration": 1
        }
      }
    }
```

to (removing the zones from each of the schedules): 

```json 
  "schedules": {
    "FrontYard": {
      "start_time": {
        "enabled": false,
        "minute": 30,
        "hour": 6,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "*",
        "cron_string": "30 6 * * *",
        "human_readable": "At 06:30 AM",
        "active": false
      },
      "zones": {
      }
    },
    "BackYard": {
      "start_time": {
        "enabled": false,
        "minute": 0,
        "hour": 18,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "SUN,MON,TUE,WED,THU,FRI,SAT",
        "cron_string": "0 18 * * SUN,MON,TUE,WED,THU,FRI,SAT",
        "human_readable": "At 06:00 PM, only on Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday",
        "active": true
      },
      "zones": {
      }
    }
```

Then ctrl-o to save, ctrl-x to exit.  

Reboot your pi and try again.   

Hopefully this resolves the issue that you cannot access the schedules page.  If it doesn't, then I may just update the code and then have you re-install.

**Comment by nebhead** [comment]
FYI: Fixed the bug and pushed the changes to main.  When a zone name is changed, the change will be updated in the schedules as well.  This should avoid the app crash.

**Comment by nealw8** [comment]
The patch above worked.hitting schedule tab brings up the page.  Should I reinstall to incoperate these changes. 
Thanks I owe you a beer.

**Comment by nebhead** [comment]
No need to re-install if you don't plan on changing the zone names in the future. :)  However, if you have the time, it might not be a bad idea to re-install to incorporate the latest update.  That way you won't run into this bug again.  Glad I could help!  Enjoy!
