### ISSUE TITLE
screwy logical

### ISSUE THREAD

**Issue by nealw8** [nebhead/irrigator#4]
Ben, sorry to bother you again but I’m having issues again. I am running a 4 relay setup;  zone gate relay 1 is on pin 29, zone _01 is on pin 31, zone_02 is on pin 32, and zone_03 is on pin 33. All relays are off in the idle state when no zones are started. 
When zone_01 is started 3 relays turn on; the zone gate relay, the zone_02 relay and the zone_03 relay.
When zone_02 is started 3 relays turn on; the zone gate relay, the zone_01 relay and the zone_03 relay. 
When zone_01 is started 3 relays turn on; the zone gate relay, the zone_01 relay and the zone_02 relay.
This is just opposite to what I would expect if the lines feeding the solenoids are on the NO feeds. Furthermore I do not under stand the role of the gate relay has. From you diagrams I interpret that in the idle state with no zones on it not feeding any power to the relays when a zone is activated this turns on the power. Am I correct?
Nealw

**Comment by nebhead** [comment]
Is your relay active low or active high?   This is one thing that I should put into the documentation, since my relays are active low (meaning writing a zero to them will switch them on/closed).

**Comment by nealw8** [comment]
I'm guessing that must be what it is.  is there a way to flip that logic?

**Comment by nebhead** [comment]
Yep, very simple. :)  Just change the below lines in `control.py` by ssh'ing into the pi and typing:

`sudo nano /usr/local/bin/irrigator/control.py`

Then change these lines from:

```python
	errorcode = errorcode + platform.setrelay(0, zonename) # Turning on Zone
```
```python
	errorcode = errorcode + platform.setrelay(1, zonename) # Turning off Zone
```

to:

```python
	errorcode = errorcode + platform.setrelay(1, zonename) # Turning on Zone
```
```python
	errorcode = errorcode + platform.setrelay(0, zonename) # Turning off Zone
```

Then `ctrl-o' to save and `ctrl-x` to exit.  No need to reboot, you can test right away.  

Let me know how it goes!

**Comment by nealw8** [comment]
nope, when I  activate any one zone all zone relays turn on.

**Comment by nebhead** [comment]
Well that is not expected.  Let's try a test manually running a zone instead of using the web UI.  Once again SSH into your pi and try the following commands:

```bash
cd /usr/local/bin/irrigator
sudo python control.py -z front -d 1 -f
```

This should turn on the zone named 'front' (I recall from your last issue that you had the zone renamed to 'front'), for one minute and force (so no weather checks are done).  

Let me know what happens when you do this.  

Thanks!

**Comment by nealw8** [comment]
when I do that all 4 relays briefly blink

**Comment by nebhead** [comment]
> when I do that all 4 relays briefly blink

That is definitely some odd behavior.  I wonder if there is some other kind of issue.  Can you check the event.log and post the latest messages from that? 

```bash
cd /user/local/bin/irrigator
cat events.log
```

**Comment by nealw8** [comment]
2023-07-12 13:25:56 Initializing Relays on Raspberry Pi.
2023-07-12 13:25:56 Current Temperature: 90F Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-07-12 13:25:56 Force run selected. Ignoring weather.
2023-07-12 13:25:56 Manual Run Selected.
2023-07-12 13:25:56 front not found in JSON file.  Exiting.
2023-07-12 13:25:56 Exiting with errorcode = 1
2023-07-12 13:25:56 ***** Control Script Ended *****
2023-07-12 13:26:53 ***** Control Script Starting *****
2023-07-12 13:26:53 Initializing Relays on Raspberry Pi.
2023-07-12 13:26:53 Current Temperature: 90F Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-07-12 13:26:53 Force run selected. Ignoring weather.
2023-07-12 13:26:53 Manual Run Selected.
2023-07-12 13:26:53 front not found in JSON file.  Exiting.
2023-07-12 13:26:53 Exiting with errorcode = 1
2023-07-12 13:26:53 ***** Control Script Ended *****
2023-07-12 13:27:04 ***** Control Script Starting *****
2023-07-12 13:27:04 Initializing Relays on Raspberry Pi.
2023-07-12 13:27:04 Current Temperature: 90F Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-07-12 13:27:04 Force run selected. Ignoring weather.
2023-07-12 13:27:04 Manual Run Selected.
2023-07-12 13:27:04 front not found in JSON file.  Exiting.
2023-07-12 13:27:04 Exiting with errorcode = 1
2023-07-12 13:27:04 ***** Control Script Ended *****

**Comment by nebhead** [comment]
OK, looks like the zone was not found for some reason.  Can you check your irrigator.json file again and send over?

**Comment by nealw8** [comment]
{
  "controls": {
    "manual_override": false,
    "active": false
  },
  "settings": {
    "target_sys": "RasPi",
    "zone_gate": 29
  },
  "wx_data": {
    "apikey": "38567408275ce16db3c925791364f96a",
    "lat": "38.9529442",
    "long": "-76.9408647",
    "location": "Hyattsville, MD, us",
    "temp_enable": true,
    "min_temp": 32,
    "max_temp": 100,
    "precip": 0.2,
    "history_enable": true,
    "history_hours": 24,
    "forecast_hours": 24,
    "forecast_enable": true,
    "forecast_history_enable": true,
    "units": "F"
  },
  "zonemap": {
    "1_front_yard": {
      "GPIO_mapping": 31,
      "enabled": true,
      "active": false
    },
    "2_back_yard_north": {
      "GPIO_mapping": 32,
      "enabled": true,
      "active": false
    },
    "3_back_yard_south": {
      "GPIO_mapping": 33,
      "enabled": true,
      "active": false
    }
  },
  "schedules": {
    "FrontYard": {
      "start_time": {
        "enabled": false,
        "minute": 30,
        "hour": 6,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "*",
        "cron_string": "30 6 * * *",
        "human_readable": "At 06:30 AM",
        "active": false
      },
      "zones": {
        "2_back_yard_north": {
          "duration": 10
        },
        "3_back_yard_south": {
          "duration": 10
        }
      }
    },
    "BackYard": {
      "start_time": {
        "enabled": false,
        "minute": 0,
        "hour": 5,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "*",
        "cron_string": "0 5 * * *",
        "human_readable": "At 05:00 AM",
        "active": false
      },
      "zones": {
        "1_front_yard": {
          "duration": 60
        },
        "2_back_yard_north": {
          "duration": 60
        },
        "3_back_yard_south": {
          "duration": 60
        }
      }
    }
  }

**Comment by nebhead** [comment]
Yep, the name changed so we need a different command:

```bash
cd /usr/local/bin/irrigator
sudo python control.py -z 1_front_yard -d 1 -f
```

**Comment by nealw8** [comment]
all 4 relays triggered for a minute

**Comment by nebhead** [comment]
OK, looks like there is one more place we need to edit:
```bash
cd /usr/local/bin/irrigator
sudo nano platform_raspi.py
```
Change the following line from:

```python
GPIO.setup(self.outpins[item], GPIO.OUT, initial=1) #Set the Zone Pins High
```

To:
```python
GPIO.setup(self.outpins[item], GPIO.OUT, initial=0) #Set the Zone Pins Low
```
Then `ctrl-o` to save and `ctrl-x` to exit. 

This time, let's reboot and try again. 

I think this is going to work.  Fingers crossed.

**Comment by nealw8** [comment]
firing on all 8 as they use to say back in the day. All relay zones activate the gate relay holds fast.
thanks

**Comment by nebhead** [comment]
Ha!  OK, progress I think?  So, when you run the command, you still see all zone relays trigger/activate?  However the gate relay does not?

**Comment by nealw8** [comment]
when I execute the following command "sudo python control.py -z 1_front_yard -d 1 -f "  zone 1 relay turns on for 1 minute  but the gate relay remains off. what I meant to say in the last post that when you activate a zone with the interface the appropriate relay responds in each case. The gate relay always remains off, never changing, Sorry for the confusion.

**Comment by nebhead** [comment]
Great!  That is expected  behavior.  The Gate pin is only to prevent spurious activation when ALL pins go high or low at the same time during power-off or boot-up.  The software doesn't actually toggle this pin at all.  It's just there to prevent situations where all pins would go active at the same time.

**Comment by nealw8** [comment]
thanks again
