### ISSUE TITLE
Anything saved/configured resets after 2 weeks

### ISSUE THREAD

**Issue by TaintedIron** [nebhead/irrigator#5]
First of all, @nebhead I love this project you made. This was my first ever raspberry pi project and was a lot of fun to setup. Great job!

So, I've been running this for a few months now. Every 2-3 week, something happens where it resets everything to default. I.e., delete my schedules, change my city/state, remove my API key. 

Not sure where to go from here. Has anyone encountered this?

This is my indicator for when it happens:
![image](https://github.com/nebhead/irrigator/assets/59463977/8914d8a7-6e7e-4ce3-b51b-4ed8f3f7f7ec)

**Comment by nebhead** [comment]
> First of all, @nebhead I love this project you made. This was my first ever raspberry pi project and was a lot of fun to setup. Great job!

Thank you!  It was one of my first ever projects too, so I appreciate that very much!

> So, I've been running this for a few months now. Every 2-3 week, something happens where it resets everything to default. I.e., delete my schedules, change my city/state, remove my API key.
> 
> Not sure where to go from here. Has anyone encountered this?

This is definitely strange and unexpected.  One thing that strikes me is that there is a script in this project that moves the logs to the logs folder on a monthly basis.  That might have something to do with this, maybe.  So maybe two things you can check.  

1.  Check your crontab (maybe paste a copy of it here).  Do this by SSH'ing into your pi, then loading the crontab: 

```bash 
sudo crontab -e
```
Copy and paste the contents of the crontab (you can ignore all of the comment text with hashtags) here so we can take a look.  

2.  Check your logs folder to see the frequency of save and see if they are corresponding to the scheduled log backups.  Again, ssh into your pi, and go to the logs folder to get the list as described below: 

```bash
cd /usr/local/bin/irrigator/logs
ls -l
```
Copy and paste the directory listing here in this thread let me know if the dates/times seem to correlate to when you see the issue.

**Comment by TaintedIron** [comment]
Thank you for the detailed walkthrough!

OUTPUT `sudo crontab -e`

```
@reboot cd /usr/local/bin/irrigator && sudo python3 control.py -i & # Irrigator-Init
@monthly cd /usr/local/bin/irrigator/logs && sh backup.sh # Irrigator-Log
*/15 * * * * cd /usr/local/bin/irrigator && sudo python3 openwx.py # Irrigator-WxCache
0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning
0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Night & # Night
0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Evening & # Evening
# 0 20 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Backyard & # Backyard
0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning
30 21 2-30/2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYard & # FrontYard
30 22 2-30/2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s BackYard & # BackYard
30 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYardMorning & # FrontYardMorning
0 6 */2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s MorningFront & # MorningFront
30 6 */2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s MorningBack & # MorningBack
```


LOGS:

```
irrigationpi@irrigationpi:~ $ cd /usr/local/bin/irrigator/logs
irrigationpi@irrigationpi:/usr/local/bin/irrigator/logs $ ls -l
total 336
-rwxr-xr-x 1 root         root            185 Apr 25 20:16 backup.sh
-rw-r--r-- 1 irrigationpi irrigationpi    329 Jun  9 11:14 backup_v2.sh
-rw-r--r-- 1 root         root         115360 Jun  7 22:50 backuplog-2023-06-07.log
-rw-r--r-- 1 root         root           5137 Jun  9 11:13 backuplog-2023-06-09.log
-rw-r--r-- 1 root         root          68550 Jun 30 22:50 backuplog-2023-07-01.log
-rw-r--r-- 1 root         root          39896 Jul 21 21:13 webapp.err.log
-rw-r--r-- 1 root         root          80469 Jul 21 11:13 webapp.out.log
```

@nebhead For educational purposes, do you mind explaining and stepping through how you are navigating this issue?
What is `sudo crontab -e` telling you? What is the significance here, `cd /usr/local/bin/irrigator/logs && ls -l`?

**Comment by nebhead** [comment]
My thought process was to jump into what could cause your system to 'reset' every two weeks.  Basically, all of the configuration data for irrigator is stored in the /usr/locl/bin/irrigator/irrigator.json file.  If you are losing all of your configuration information, then it's likely that this file is being erased every couple of weeks.  My only thought was that maybe there was some script running every two weeks, like the log backup script, that might be clobbering the JSON file mentioned above.  Thus, I wanted to see the scheduled items in your system.  Crontab is software in the base system that will fire off commands at specific times.  Each line of the crontab represents a command that is being executed at a specific time.  Looking through yours, I don't see anything amiss.  The scheduled tasks look fine to me.  

> ```
> @reboot cd /usr/local/bin/irrigator && sudo python3 control.py -i & # Irrigator-Init
> @monthly cd /usr/local/bin/irrigator/logs && sh backup.sh # Irrigator-Log
> */15 * * * * cd /usr/local/bin/irrigator && sudo python3 openwx.py # Irrigator-WxCache
> 0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning
> 0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Night & # Night
> 0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Evening & # Evening
> # 0 20 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Backyard & # Backyard
> 0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning
> 30 21 2-30/2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYard & # FrontYard
> 30 22 2-30/2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s BackYard & # BackYard
> 30 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYardMorning & # FrontYardMorning
> 0 6 */2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s MorningFront & # MorningFront
> 30 6 */2 * * cd /usr/local/bin/irrigator && sudo python3 control.py -s MorningBack & # MorningBack
> ```
 
I also wanted to see the logs folder to see if I could see an emerging pattern for when the logs were written.  The only two outliers are the logs that were backed up on 06/07 and 06/09 which is interesting, but don't really correlate to the behavior that you are seeing.  

> ```
> irrigationpi@irrigationpi:~ $ cd /usr/local/bin/irrigator/logs
> irrigationpi@irrigationpi:/usr/local/bin/irrigator/logs $ ls -l
> total 336
> -rwxr-xr-x 1 root         root            185 Apr 25 20:16 backup.sh
> -rw-r--r-- 1 irrigationpi irrigationpi    329 Jun  9 11:14 backup_v2.sh
> -rw-r--r-- 1 root         root         115360 Jun  7 22:50 backuplog-2023-06-07.log
> -rw-r--r-- 1 root         root           5137 Jun  9 11:13 backuplog-2023-06-09.log
> -rw-r--r-- 1 root         root          68550 Jun 30 22:50 backuplog-2023-07-01.log
> -rw-r--r-- 1 root         root          39896 Jul 21 21:13 webapp.err.log
> -rw-r--r-- 1 root         root          80469 Jul 21 11:13 webapp.out.log
> ```

I have a couple of other theories to pursue.  One is that we might be dealing with a misbehaving SDCard or either the OS or irrigator installation is corrupted somehow.  The other is that there may be an issue with loading of the settings data, causing it to load in a fresh copy instead (this might actually be related to an SDCard issue).  

So next steps are for me to take a look at that code that reads the settings file and see if I can modify it someway.  The other next step for you may be to either find a new SDCard to try, or to wipe your current SDCard and start fresh.  Consider you may need to re-apply some of the code changes you have made already.

**Comment by nebhead** [comment]
Looking at the code, it's definitely possible that there was an issue loading the irrigator.json file and it decided to re-write a new copy.  We can check for this in the events.log file and look for the text `Exception occured when reading irrigator.json.  Creating the file with default settings.`

The events.json file is found /usr/local/bin/irrigator/events.log.  However, I suspect that this line may be contained in one of the previous backups which would be in /usr/local/bin/irrigator/logs.  

Perhaps take a look at backuplog-2023-06-07.log or backuplog-2023-06-09.log and let me know if you see something that looks like the above wording in there.  If we see that, I think we are closer to a smoking gun.  

FYI, you can see the contents of these files using `cat` or `nano`: 
```
cd /usr/local/bin/irrigator/logs
cat backuplog-2023-06-07.log
```
Or in the editor nano:
```
cd /usr/local/bin/irrigator/logs
nano backuplog-2023-06-07.log
```


Thanks!

**Comment by TaintedIron** [comment]
I found the below in backuplog-23-06-07.log:

`2023-06-07 06:00:03 Exception occured when reading irrigator.json.  Creating the file with default settings.`

**Comment by TaintedIron** [comment]
FYI:

```
cat /etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by nebhead** [comment]
> I found the below in backuplog-23-06-07.log:
> 
> `2023-06-07 06:00:03 Exception occured when reading irrigator.json. Creating the file with default settings.`

Yep, I think this might be what is happening.  Sometimes, in rare cases, if the front end is reading the settings file at the same time that the backend is reading the file, an error occurs.  When one is reading from the file, the other is blocked and will throw up an error, then reset the file back to defaults.   I suspect this is what might have happened here.  I have some ideas for workarounds that I can apply... and maybe fix your other changes at the same time.  Might need a few days to get to it though.   In the meantime, I'd say backup your irrigator.json file so if this happens again before I'm able to deploy a fixed version, you will simply be able to overwrite the irrigator.json with your settings.

**Comment by nebhead** [comment]
@TaintedIron - OK, I think I resolved this issue.  I was able to reproduce on my end and have a workaround for now.  I've pushed the latest to github so you can grab it and try it.  There should be no need to re-install, and you should be able to do this from the command line. 

```bash
cd /user/local/bin/irrigator
sudo git fetch --all
sudo git reset --hard origin/main
```
(this should force an update and overwrite your changes - hopefully it works on your end)

Also, I've added 'Relay Trigger Level' to the settings so you don't have to modify your code anymore.  Just set your Relay Trigger Level to 'Active High Trigger' in the settings after you do the update.  

![image](https://github.com/nebhead/irrigator/assets/19876886/9556cd1a-785f-4676-a9ef-19f9793a2162)

Let me know how it goes!

**Comment by TaintedIron** [comment]
@nebhead - Thank you very much for helping with this. I updated the repo with the commands above and haven't encountered any issues. Would you like me to close this issue and reopen if need be?

> Also, I've added 'Relay Trigger Level' to the settings so you don't have to modify your code anymore. Just set your Relay Trigger Level to 'Active High Trigger' in the settings after you do the update.

What does this do exactly? Last question, kind of a loaded question, after reproducing my issue how did you locate where the code was breaking in your recent commit 4bba62d?

**Comment by nebhead** [comment]
> @nebhead - Thank you very much for helping with this. I updated the repo with the commands above and haven't encountered any issues. Would you like me to close this issue and reopen if need be?

Sounds good!  Happy to help.  

> What does this do exactly? 

Since you have active High relays (relays that are 'ON' when you send a 1 or HIGH to them), the code needs to reverse the logic in your case.  I have active Low relays (relays that are 'ON' when you send a 0 or LOW to them), so I had designed the code to behave appropriately for those.  To accommodate both scenarios, I've added a switch to the settings so anyone can select what kind of relays they have and it should work.  This way you don't need to go modify the code like you did in your previous sighting.  

> Last question, kind of a loaded question, after reproducing my issue how did you locate where the code was breaking in your recent commit [4bba62d](https://github.com/nebhead/irrigator/commit/4bba62d5b222f1d4992b63040957b55374cd6467)?

So the last commit was actually an additional issue I discovered while investigating your issue.  I noticed that I was getting a timeout error and was losing the long/lat in the settings due to the timeout with the geo-location interface/API.  Anyway, I fixed this in addition to your sighting regarding the settings being lost in general.  

As for the issue that you pointed out (thank you by the way).  I have seen issues with reading the settings file in other projects, but not in this one.  It's likely because my setup is simpler than yours and it is less likely for me to run into the issue where the settings file is being read by two different processes at the same time.  Anyway, when this happens, the code assumes that there is something very bad with the file and it writes it all to defaults again.  This is what caused you to lose your settings.  My fix is to continuously retry when getting this very specific error, instead of resetting the file to defaults.  

Hope this helps!  But feel free to ask any follow up questions.  Always happy to share.

**Comment by TaintedIron** [comment]
What is the difference between High and Low active relays? How could you tell I have active High relays?

Additionally, I believe the program is behaving as it should. I'm seeing a backup log was created at the beginning of the month. Below is a snapshot of last night's log:

```
2023-08-03 | 21:00:03 | ***** Control Script Starting *****
2023-08-03 | 21:00:03 | Exception occurred when reading irrigator.json. Value Error Exception - JSONDecodeError. Retrying.
2023-08-03 | 21:00:03 | Exception occurred when reading irrigator.json. Value Error Exception - JSONDecodeError. Retrying.
2023-08-03 | 21:00:03 | Exception occurred when reading irrigator.json. Value Error Exception - JSONDecodeError. Retrying.
2023-08-03 | 21:00:03 | Initializing Relays on Raspberry Pi.
2023-08-03 | 21:00:04 | Initializing Relays on Raspberry Pi.
2023-08-03 | 21:00:04 | Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-08-03 | 21:00:04 | Schedule Run Selected with Schedule: Night
2023-08-03 | 21:00:04 | Night not found in JSON file. Exiting Now.
2023-08-03 | 21:00:04 | Exiting with errorcode = 1
2023-08-03 | 21:00:04 | ***** Control Script Ended *****
```

Again, thank you for your help and willingness to share your knowledge!

**Comment by TaintedIron** [comment]
@nebhead hope all is well! I reopened this issue due to a new one; I'm not sure if it's related to the original issue here but wanted your opinion. 

I noticed last night zone 2 was _active_ outside of it's schedule. I looked out the window and noticed it was not running. This morning I rebooted the RPi and still have this issue. Below is a snip of the 8/9/23 logs and what I'm seeing.

```
2023-08-09 06:00:04 ***** Control Script Starting *****
2023-08-09 06:00:04 ***** Control Script Starting *****
2023-08-09 06:00:04 Initializing Relays on Raspberry Pi.
2023-08-09 06:00:04 Initializing Relays on Raspberry Pi.
2023-08-09 06:00:04 Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-08-09 06:00:04 Schedule Run Selected with Schedule: Morning
2023-08-09 06:00:04 Morning not found in JSON file.  Exiting Now.
2023-08-09 06:00:04 Exiting with errorcode = 1
2023-08-09 06:00:04 ***** Control Script Ended *****
2023-08-09 06:00:04 Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-08-09 06:00:04 Schedule Run Selected with Schedule: Morning
2023-08-09 06:00:04 Morning not found in JSON file.  Exiting Now.
2023-08-09 06:00:04 Exiting with errorcode = 1
2023-08-09 06:00:04 ***** Control Script Ended *****
2023-08-09 06:30:03 ***** Control Script Starting *****
2023-08-09 06:30:03 Initializing Relays on Raspberry Pi.
2023-08-09 06:30:03 Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-08-09 06:30:03 Schedule Run Selected with Schedule: FrontYardMorning
2023-08-09 06:30:03 FrontYardMorning not found in JSON file.  Exiting Now.
2023-08-09 06:30:03 Exiting with errorcode = 1
2023-08-09 06:30:03 ***** Control Script Ended *****
2023-08-09 13:15:05 Error getting data from Geolocator, using stored Lat/Long instead.
2023-08-09 14:00:05 Error getting data from Geolocator, using stored Lat/Long instead.
2023-08-09 14:15:05 Error getting data from Geolocator, using stored Lat/Long instead.
2023-08-09 21:00:03 ***** Control Script Starting *****
2023-08-09 21:00:03 ***** Control Script Starting *****
2023-08-09 21:00:03 Initializing Relays on Raspberry Pi.
2023-08-09 21:00:04 Initializing Relays on Raspberry Pi.
2023-08-09 21:00:04 Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-08-09 21:00:04 Schedule Run Selected with Schedule: Night
2023-08-09 21:00:04 Night not found in JSON file.  Exiting Now.
2023-08-09 21:00:04 Exiting with errorcode = 1
2023-08-09 21:00:04 Precipitation History: 0.0 inches Precipitation Forecast: 0.0 inches
2023-08-09 21:00:04 Schedule Run Selected with Schedule: Evening
2023-08-09 21:00:04 Evening not found in JSON file.  Exiting Now.
2023-08-09 21:00:04 Exiting with errorcode = 1
2023-08-09 21:00:04 ***** Control Script Ended *****
2023-08-09 21:00:04 ***** Control Script Ended *****
```
![image](https://github.com/nebhead/irrigator/assets/59463977/c5c8f6a3-ca12-4061-8d2f-468a13c09178)

**Comment by nebhead** [comment]
It looks like there may be some older schedules in the crontab that maybe need to be cleared up.  Or perhaps maybe a fresh install is needed.  

Maybe take a screenshot of the schedules page, so that I can see what schedules you have in the JSON file.  Or alternatively just send the schedules section of the irrigator.json file.  Then like before, check the crontab with `sudo crontab -l` and share the contents here.  

I suspect there may be some older schedules in there that aren't in the file.

**Comment by TaintedIron** [comment]
```
  "schedules": {
    "FrontYard": {
      "start_time": {
        "enabled": true,
        "minute": 30,
        "hour": 21,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "Sun,Tue,Thu",
        "cron_string": "30 21 * * Sun,Tue,Thu",
        "human_readable": "At 09:30 PM, only on Sunday, Tuesday, and Thursday",
        "active": true
      },
      "zones": {
        "zone_01": {
          "duration": 20
        },
        "zone_02": {
          "duration": 40
        },
        "zone_03": {
          "duration": 0
        }
      }
    },
    "BackYard": {
      "start_time": {
        "enabled": true,
        "minute": 0,
        "hour": 23,
        "day_of_month": "*",
        "month": "*",
        "day_of_week": "Sun,Tue,Thu",
        "cron_string": "0 23 * * Sun,Tue,Thu",
        "human_readable": "At 11:00 PM, only on Sunday, Tuesday, and Thursday",
        "active": false
      },
      "zones": {
        "zone_01": {
          "duration": 0
        },
        "zone_02": {
          "duration": 0
        },
        "zone_03": {
          "duration": 40
        }
      }
    }
  }
```

```
@reboot cd /usr/local/bin/irrigator && sudo python3 control.py -i & # Irrigator-Init
@monthly cd /usr/local/bin/irrigator/logs && sh backup.sh # Irrigator-Log
*/15 * * * * cd /usr/local/bin/irrigator && sudo python3 openwx.py # Irrigator-WxCache
0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning
0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Night & # Night
0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Evening & # Evening
# 0 20 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Backyard & # Backyard

0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning

30 21 * * Sun,Tue,Thu cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYard & # FrontYard
0 23 * * Sun,Tue,Thu cd /usr/local/bin/irrigator && sudo python3 control.py -s BackYard & # BackYard

30 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYardMorning & # FrontYardMorning
```

**Comment by nebhead** [comment]
Yeah, so you have only two schedules actually in the irrigator.json file that are defined.  These are the default front yard and backyard schedules that are installed when you installed (or re-installed).  

However, in the crontab (the OS scheduling software), you have other schedules being called like Morning, Night, Evening and FrontYardMorning.  Those need to be defined in the web interface (i.e. in the irrigator.json file).  My suggestion would be to first edit your crontab to delete all of the schedule lines: 

`sudo crontab -e`

Then remove these lines: 

```
0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning
0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Night & # Night
0 21 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Evening & # Evening
# 0 20 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Backyard & # Backyard

0 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s Morning & # Morning

30 21 * * Sun,Tue,Thu cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYard & # FrontYard
0 23 * * Sun,Tue,Thu cd /usr/local/bin/irrigator && sudo python3 control.py -s BackYard & # BackYard

30 6 * * * cd /usr/local/bin/irrigator && sudo python3 control.py -s FrontYardMorning & # FrontYardMorning
```
Save and Close.

Then in the WebUI, delete the FrontYard and BackYard schedules.  Next, add your desired schedules/zones.  This should clear up any issues.  

You can check your crontab again `sudo crontab -l`.  It should then match up to your schedules that you just created.  

Hope this helps!  Let me know if you have more questions.

**Comment by TaintedIron** [comment]
I've been attempting to retest everything the past few weeks but had multiple setbacks with fixing my well pump. Now with everything in order, I believe my relay board is fried. I see 24v on the multimeter for my hot wire, but when starting a zone you don't see any volts being delivered through the relay. I'm almost certain this is the issue. 

Do you have any suggestions for reliable 8-channel relay board? Any pros/cons for Active high or Active low boards?

**Comment by nebhead** [comment]
> Do you have any suggestions for reliable 8-channel relay board? Any pros/cons for Active high or Active low boards?

Unfortunately, I've had challenges with the cheap maker relay boards in the past as well.  They can be a bit hit or miss sometimes (especially when ordering directly from China - AliExpress, etc.).  I haven't really found a good alternative, unfortunately, short of building your own relay module.  So perhaps just order another from Amazon and hopefully it will last.  The one I currently am using in my sprinkler project has actually been going strong since 2016!  So when you do find a good one, they can last if you are lucky.   (just watch, it'll die tomorrow because I said this. :P)

**Comment by TaintedIron** [comment]
I've finally been able to put this back together. New SD card, new RPi Zero W, and a new 8 Channel Relay. After assembling, I haven't been abled to get it working. My wiring is setup like the picture in the README file. Is there anything different that needs to be setup for a low active relay board? This is what I'm using [https://www.amazon.com/gp/product/B00LW2GA5Y/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1](url)

**Comment by nebhead** [comment]
Have you gone into your settings and selected Active Low Trigger?  

![image](https://github.com/nebhead/irrigator/assets/19876886/cc0da147-d538-4281-81fa-43f3849db65f)

Mine is active low as well, so it should work just fine with the wiring from the schematic on GitHub.

**Comment by nebhead** [comment]
> [https://www.amazon.com/gp/product/B00LW2GA5Y/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1](url)

I just checked this link and this relay is 12V which will not work with the Raspberry Pi.  You'd need to level shift to get this to work.   What you need is a 5V relay.  Maybe something like this: https://www.amazon.com/SunFounder-Channel-Shield-Raspberry-Arduino/dp/B00DR9SE4A

**Comment by TaintedIron** [comment]
I can't believe I made that mistake. Looks like the same brand makes both 12v and 24v. Thank you for pointing that out!
