### ISSUE TITLE
Cannot get power to sprinkler valve with new Low Active Relay

### ISSUE THREAD

**Issue by TaintedIron** [nebhead/irrigator#7]
Cannot seem to get this Low Active Relay to work with new install of irrigator. I have a new Pi Zero, new SD card, new low active relay, and new power supply. I have this setup the same way I did before which is the recommended wiring in the README. Below are some pictures of my wiring and testing.  

Relay used: [https://www.[amazon.com/dp/B09TYKWHPV?psc=1&ref=ppx_yo2ov_dt_b_product_details](https://www.amazon.com/dp/B09TYKWHPV?psc=1&ref=ppx_yo2ov_dt_b_product_details)](url)

**Comment by TaintedIron** [comment]
![IMG_2753](https://github.com/nebhead/irrigator/assets/59463977/a72a6c28-ea17-4dd3-b3cd-eace15cf03a9)
![IMG_2754](https://github.com/nebhead/irrigator/assets/59463977/85ac93af-5e48-4858-bc66-1f3760924f88)
![IMG_2755](https://github.com/nebhead/irrigator/assets/59463977/769db9fb-6b4b-4b1e-b00a-dc63c77b9707)
![IMG_2756](https://github.com/nebhead/irrigator/assets/59463977/46570d26-33bc-4171-ad5a-ffbdab39d33a)
![IMG_2757](https://github.com/nebhead/irrigator/assets/59463977/bb3d9690-d7e0-4151-8328-58077783c806)

**Comment by nebhead** [comment]
> Cannot seem to get this Low Active Relay to work with new install of irrigator. I have a new Pi Zero, new SD card, new low active relay, and new power supply. I have this setup the same way I did before which is the recommended wiring in the README. Below are some pictures of my wiring and testing.
> 
> Relay used: [https://a.co/d/1opIg6M](url)

I hate to be the bearer of bad news, but that relay is a 24V relay.  It needs to be a ***5V*** relay or it will not work with the Raspberry Pi.  You need a 5v INPUT relay like this one: https://www.amazon.com/HiLetgo-Channel-OPTO-Isolated-Support-Trigger/dp/B00LX3UH9C/

**Comment by TaintedIron** [comment]
My goodness...I should've caught that. After this I will be an expert in relays. Thank you for your help @nebhead !!

**Comment by TaintedIron** [comment]
After being sent the wrong relay twice, the third one is a charm. Everything is hooked up and powering on correctly. When testing voltage on the relay prior to turning on a zone I read 24v on COM and NC. After turning on zone 1, I hear the auditable switch of the relay and see the relay LED turn on. Although, on my Gate Relay (relay 1) I read no voltage on NC which in turn does not supply Zone 1 (Relay 2) with any power.

**Comment by nebhead** [comment]
Great, glad to hear you are making progress.  

Are your relays active low or active high?  Are you setting that appropriately in the settings page? 

Have you wired your system as in the documentation?  

https://github.com/nebhead/irrigator#schematics

The GATE pin / relay should never activate.  It's only there to be a gate if all relays decide to flip at once (i.e. during boot).  

Since the GATE is on the always connected (or normally connected) terminal, that means it will always be hot UNLESS, some other software changes the state of the pin.  This can happen during boot where we don't know the state of the output pins, and they may all transition at the same time to 0 or to 1.  If this happens, then the GATE has the reverse logic of the rest of the ZONE pins and will prevent a spurious relay from turning on.  

So normal behavior would be that the GATE is always supplying 24V to the other relays common pin.  You should be able to measure 24V AC on those pins all the time.  The ZONEs will activate only when we activate them (which sounds like is working in your case).  This means you will see 24V on the NO (Normally Open) pin of that relay when activated.  

Hopefully this helps.

**Comment by TaintedIron** [comment]
I am using an active low relay and selected in settings. [https://www.amazon.com/dp/B07XM5GVWJ?ref=ppx_yo2ov_dt_b_product_details&th=1](url). Additionally, the system is wired exactly like the documentation.

For this relay board, I have the RPi 5v pin going to DC+ and ground pin going to DC-. Assuming this is correctly configured.

**Comment by nebhead** [comment]
Do you have a multi-meter, can you measure the AC voltage on all the common pins and verify that they are all getting 24V from your 24V AC supply?

**Comment by TaintedIron** [comment]
I currently have relays 0 (gate) and 1 (zone 1) setup. Both relays are reading 24v on NC and COM.

**Comment by nebhead** [comment]
> I currently have relays 0 (gate) and 1 (zone 1) setup. Both relays are reading 24v on NC and COM.

That is what would be expected, until the zone1 relay is activated.  If zone 1 is activated, then you should see 24V on the NC/COM of the gate relay and on the NO/COM of the Zone 1.

**Comment by TaintedIron** [comment]
This is where the issue occurs. If zone 1 activated, I don't see 24V on the NC/COM of the gate relay or on the NO/COM of the Zone 1. I'm not sure if this matters, but in the same instance the LED indicator for both relays turn on.

**Comment by nebhead** [comment]
> I'm not sure if this matters, but in the same instance the LED indicator for both relays turn on.

Yes, this definitely matters, thanks for pointing this out.  The gate relay should not be turning on in this instance.  I wonder why this is going active low when you engage zone 1.  How do you the DC side hooked up?  Are you ensuring that you have the right gate pin defined in the settings?   Maybe share a screenshot of your settings for gate and zone 1.  Do you have any other zone relays hooked up?  I wonder if they all behave the same way?

**Comment by TaintedIron** [comment]
Correction, when activating Zone 1 earlier today, I only saw the LED light for the Gate Relay. I forgot to mention what I observed a few days ago. If zone 1 activated LED for gate relay and zone 2 light up, and if zone 2 activated the LED for gate relay and zone 1 light up. Seen in pictures below.

settings:
`{
  "controls": {
    "manual_override": false,
    "active": false
  },
  "settings": {
    "target_sys": "RasPi",
    "zone_gate": 29,
    "relay_trigger": 0
  },
  "zonemap": {
    "zone_01": {
      "GPIO_mapping": 31,
      "enabled": true,
      "active": false
    },
    "zone_02": {
      "GPIO_mapping": 32,
      "enabled": true,
      "active": false
    },
    "zone_03": {
      "GPIO_mapping": 33,
      "enabled": true,
      "active": false
    }`

Hardware & wiring configuration:
purple is pin 29
green is pin 31
blue is pin 32

note, blue was connected after picture

![hardware](https://github.com/nebhead/irrigator/assets/59463977/fe932006-dc55-4aa2-a5a0-8be574b3545a)
![wiring](https://github.com/nebhead/irrigator/assets/59463977/152440d3-6115-4825-ab0c-a1414f8c1044)
![gpio](https://github.com/nebhead/irrigator/assets/59463977/60fe3a47-fbd5-46b7-8ae1-75692195999d)

zone 1 activated:
![zone1_activated](https://github.com/nebhead/irrigator/assets/59463977/e1d8a28e-187e-49cb-805b-6338183f31f3)

zone 2 activated:
![zone2_activated](https://github.com/nebhead/irrigator/assets/59463977/19bb773d-9d83-470f-97b7-48b62be8e3ea)

**Comment by nebhead** [comment]
It looks like your relays might be configured for active high.  I'm not super familiar with that type of relay, but I think the yellow jumper blocks let you configure each relay to be active high or low.  Can you double check those?

**Comment by TaintedIron** [comment]
> I think the yellow jumper blocks let you configure each relay to be active high or low.

I didn't realize this board already had jumper caps on them. Reading the description on amazon, I adjusted S1-S3 to Low Active for the first 3 relays. Same issue occurs when activating zone 1. I thought this would be the fix but this seems to be very odd.

**Comment by nebhead** [comment]
OK, let's recap then, what steps are you walking through when you do the test?

**Comment by TaintedIron** [comment]
After boot, I ensure I can access the http server in my browser. Then I double check my settings I.e., target system, verify GPIO pins, and select low active relay. 

Then checking my hardware, I start with 5V and GND are connected to DC+ and DC- on the relay board. Next I check Pin 29 is goes to Relay 0, Pin 31 going to Relay 1, and Pin 32 is going to Relay 2. 

Lastly, I make sure my 24V power supply is connected to a small bus bar. Then following the hot wire down to Relay 0 NC. Here is when I check my volts with a multimeter. First checking power at the bus bar, and on each COM ports. 

For the test, I have a 24V solenoid connected to zone 1 and I manually turn on zone 1 in my browser. 

Hope this is helpful.

**Comment by nebhead** [comment]
Thank you!  And the behavior is the same when you configure all the relays to active low on the relay module and in the software, correct?  Basically what happens is that the Gate relay activates AND the Zone 2 relay activates but not Zone 1?  Or does Zone 1 activate?

**Comment by TaintedIron** [comment]
> And the behavior is the same when you configure all the relays to active low on the relay module and in the software, correct?

I've only tested Zone 1 & Zone 2, so the first 3 relays including the Gate Relay. All 3 are configured for active low.

> Basically what happens is that the Gate relay activates AND the Zone 2 relay activates but not Zone 1? Or does Zone 1 activate?

For these 3 relays, if I activate zone 1 the LED for Gate & Zone 2 lights up. If I activate Zone 2 the LED for Gate & Zone 1 lights up.

**Comment by nebhead** [comment]
> > And the behavior is the same when you configure all the relays to active low on the relay module and in the software, correct?
> 
> I've only tested Zone 1 & Zone 2, so the first 3 relays including the Gate Relay. All 3 are configured for active low.
> 
> > Basically what happens is that the Gate relay activates AND the Zone 2 relay activates but not Zone 1? Or does Zone 1 activate?
> 
> For these 3 relays, if I activate zone 1 the LED for Gate & Zone 2 lights up. If I activate Zone 2 the LED for Gate & Zone 1 lights up.

This sounds like opposite logic is happening somehow.  What the software should be doing is:

Initializing all of the relay outputs to the opposite of the active logic.  So if it's configured for active low, then it should set all relays to a '1' (not '0').  Then it will activate the relay that was selected and write the active logic value to that relay output, so again for active low, it will write a '0' to that output.   

In your case, it looks like it's initializing all of the relays to active and then de-activating the correct relay.  So let's try this.  Go to the settings and flip it to active high, just for giggles, and then save and try to run through this again to see what happens.

**Comment by TaintedIron** [comment]
> So let's try this. Go to the settings and flip it to active high, just for giggles, and then save and try to run through this again to see what happens.

After further reading into active logic the past week I actually did give this a try to see if there was a change in output. Activating Zone 1 I remember observing all the LEDs turning on. Although, this was before changing the jumper caps from high to low.

**Comment by nebhead** [comment]
Yeah, give this a try now that you have the jumpers changed.  I'm just trying to make sense of the logic here.  It doesn't sound like it's behaving in a predictable way, so I'm trying to build a truth table. 

_With Active Low Logic Selected:_

-> Activate Zone 1 
Gate Relay - ON
Zone 1 Relay - OFF
Zone 2 Relay - ON

_With Active High Logic Selected:_

-> Activate Zone 1 
Gate Relay - ?
Zone 1 Relay - ?
Zone 2 Relay - ?

**Comment by TaintedIron** [comment]
> With Active High Logic Selected:
-> Activate Zone 1
Gate Relay - ?
Zone 1 Relay - ?
Zone 2 Relay - ?

I didn't have enough time last night to figure this out, but upon boot without doing anything I noticed Zone 1 and Zone 2 were active. So, I wasn't able to properly test this because I was unable to turn off the zones. Any idea why?

**Comment by nebhead** [comment]
> I didn't have enough time last night to figure this out, but upon boot without doing anything I noticed Zone 1 and Zone 2 were active. So, I wasn't able to properly test this because I was unable to turn off the zones. Any idea why?

The normal 'off' state, is of course, that all relays should by 'off' or inactive.  When the software boots up, it should initialize the relays to what it thinks are an off state.  This means it will program the relay outputs to the opposite of the active signal.  So if it's active high, it will program relays to zero, if it's active low it will program the relays to one.  

In your case, I would guess that the relays are perhaps reversed and are getting programmed to on when you turn on the system.  Just a guess, but we will have to do more testing.

**Comment by TaintedIron** [comment]
Alright...Everything is good to go. nothing weird going on in the UI. I tested the second scenario with relay board jumper caps set to Active High. 

With Active High Logic Selected:
-> Activate Zone 1
Gate Relay - ON
Zone 1 Relay - ON
Zone 2 Relay - ON

-> Activate Zone 2
Gate Relay - ON
Zone 1 Relay - ON
Zone 2 Relay - ON


After observing this, I selected Active Low Logic in the settings and rebooted to retest first scenario. I observed different results than I did on Tuesday.

With Active Low Logic Selected:
-> Activate Zone 1
Gate Relay - ON
Zone 1 Relay - ON
Zone 2 Relay - ON

-> Activate Zone 2
Gate Relay - ON
Zone 1 Relay - ON
Zone 2 Relay - ON

**Comment by nebhead** [comment]
So do the relays turn off at any time?  Or are they seemingly all on, all the time?

**Comment by TaintedIron** [comment]
They are all off on boot. They LEDs turn on when activating a zone as described in the last comment.

**Comment by nebhead** [comment]
Well, I have to say I am a bit stumped here.  Let's maybe go back to your irrigator.json file and make sure things are setup correctly.  Can you maybe send me an excerpt of that like you did previously?   

The only thing I can think is that, these relays aren't behaving like the old school relay modules (like [this one](https://www.amazon.com/SunFounder-Channel-Shield-Raspberry-Arduino/dp/B00DR9SE4A)).  Maybe this relay module really needs an 5V signal to switch.  It's still weird that it would activate all relays regardless of being in active high or active low trigger mode.

**Comment by TaintedIron** [comment]
> old school relay modules (like [this one](https://www.amazon.com/SunFounder-Channel-Shield-Raspberry-Arduino/dp/B00DR9SE4A))

I ended up buying one of these over the weekend. This is what I was using originally. This morning I wired it all up and my sprinklers are back online. I think I'm going to stick with this one. Also, one thing I noticed with this new board is it is working with Active Low selected. Before I was using Active High for this relay board.

**Comment by nebhead** [comment]
> I ended up buying one of these over the weekend. This is what I was using originally. This morning I wired it all up and my sprinklers are back online. I think I'm going to stick with this one. 

Great!  I guess those new selectable relays are just not going to work without level shifters.  Good to know! 

> Also, one thing I noticed with this new board is it is working with Active Low selected. Before I was using Active High for this relay board.

Yep, these types come in two flavors and generally will tell you in the product description.  It looks like this one does not though which is a little annoying.

**Comment by TaintedIron** [comment]
I appreciate you help with this @nebhead. I wish we were able to figure this out, but my wife is very happy to see the yard getting watered again! lol
