### ISSUE TITLE
problems bringing up dash board

### ISSUE THREAD

**Issue by nealw8** [nebhead/irrigator#8]
Ben,
It's me again, I did a new install because the weather grabber was not working. All went well with the re-install except I was not able to access the dashboard via the address found with an IP scanner (got a 502 bad gateway), but i can get in via SSHing,
Did I miss something in the re-install?
Neal

**Comment by nebhead** [comment]
No problem.  What version of the OS did you install this time?  Raspberry Pi introduced a new OS called Bookworm which will definitely NOT work with the current installer.  I'd recommend flashing with Raspberry Pi OS Lite 'Legacy' (32 or 64 bit depending on your Pi).

**Comment by nealw8** [comment]
raspberry pi OS (legacy 32 bit)
port of Debian bullseye

**Comment by nealw8** [comment]
by the way the install went with out a hitch
unlike the last time

**Comment by nebhead** [comment]
Alright, let's try SSH'ing into your Pi and checking the installed Python packages.  

run 'pip list' and send over the output.  My next theory is that the wrong version of Flask got installed, but let's check.

**Comment by nealw8** [comment]
![image](https://github.com/nebhead/irrigator/assets/138899789/e8c92e1f-9a5a-45e8-be33-a6b3d6de5791)
here's a screen shot

**Comment by nebhead** [comment]
Interesting... no flask at all!  I wonder what happened there.  Looks like none of the python modules were installed correctly.  Maybe try to manually install them.

`sudo pip install flask python-crontab cron-descriptor requests geopy`

**Comment by nealw8** [comment]
This is what we see
nealw@irrigator:~ $ sudo pip install flask python-crontab cron-descriptor requests geopysudo pip install flask python-crontab cron-descriptor requests geopy
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by nebhead** [comment]
Whoa, this is happening on Bullseye?!  This is the new feature I was talking about on Bookworm that is making life more difficult.  Can you do a quick dump of your os-release file? 

`cat /etc/os-release`

**Comment by nealw8** [comment]
nealw@irrigator:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by nebhead** [comment]
OK, that makes sense, so you _are_ on Bookworm.  I would highly recommend going back and re-flashing again.  It will be listed as 'legacy' in the raspberry pi image tool.  

![image](https://github.com/nebhead/irrigator/assets/19876886/6671f609-27c1-41f9-b7a8-2c7aa338426e)

**Comment by nealw8** [comment]
WILCO but that is the one I think i used

**Comment by nealw8** [comment]
well apparently I didn't load the right OS because every thing is working now. Sorry to bother you with stupidity. Thanks again.

**Comment by nebhead** [comment]
Not stupid!  If anything, it's the decisions that Debian OS made to move to forcing Python virtual environments.  Anyway, enjoy - hope this helps you keep the garden green this summer.  :+1:
